mental_health/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home_page#show'

  ###################### USER ###################################
  get '/user/registration', to: 'registration_user#new'
  post '/user/registration', to: 'registration_user#create'
  get '/user/registration/verify', to: 'registration_user#edit'
  patch '/user/registration/verify', to: 'registration_user#update'
  get '/user/resend', to: 'registration_user#resend'
  delete '/user/destroy', to: 'registration_user#destroy'

  get '/user/login', to: 'login_user#new'
  post '/user/login', to: 'login_user#create'
  post '/user/logout', to: 'login_user#logout'

  get '/user/reset_password', to: 'reset_user_password#new'
  post '/user/reset_password', to: 'reset_user_password#create'
  get '/user/reset_password/verify', to: 'reset_user_password#edit'
  patch '/user/reset_password/verify', to: 'reset_user_password#update'
  get '/user/resend_reset', to: 'reset_user_password#resend'

  get '/user/dashboard', to: 'user#dashboard'
  get '/user/dashboard/:technique_id/step/:step_id', to: 'technique#technique_detail', as: 'user_technique_detail'
  patch '/user/dashboard/:technique_id/restart', to: 'technique#restart_technique', as: 'user_technique_restart'
  get '/user/dashboard/:technique_id/rate', to: 'technique#modal_finish_technique', as: 'user_technique_rate_modal'
  post '/user/dashboard/:technique_id/rate', to: 'technique#rate_technique', as: 'user_technique_rate'

  get '/user/edit_profile', to: 'user#edit'
  patch '/user/edit_profile', to: 'user#update'
  get '/user/edit_password', to: 'user#edit_password'
  patch '/user/edit_password', to: 'user#update_password'

  get 'user/coaches', to: 'user#coaches_page', as: 'user_coaches_page'
  get 'user/coaches/invitation/:coach_id', to: 'invitation#modal_send_invitation', as: 'user_send_invitation'
  post 'user/coaches/invitation/:coach_id', to: 'invitation#send_invitation', as: 'user_send_invitation_verify'

  get 'user/coaches/cancel_invitation', to: 'invitation#modal_cancel_invitation', as: 'user_cancel_invitation'
  delete 'user/coaches/cancel_invitation', to: 'invitation#cancel_invitation', as: 'user_cancel_invitation_verify'

  get '/user/dashboard/end_coop', to: 'invitation#modal_end_cooperation', as: 'user_end_coach_cooperation'
  delete '/user/dashboard/end_coop', to: 'invitation#end_cooperation', as: 'user_end_coach_cooperation_verify'

  get '/user/techniques', to: 'user#techniques'


  ############### COACH #####################################
  get '/coach/registration', to: 'registration_coach#new'
  post '/coach/registration', to: 'registration_coach#create'
  get '/coach/registration/verify', to: 'registration_coach#edit'
  patch '/coach/registration/verify', to: 'registration_coach#update'
  get '/coach/resend', to: 'registration_coach#resend'
  delete '/coach/destroy', to: 'registration_coach#destroy'

  get '/coach/login', to: 'login_coach#new'
  post '/coach/login', to: 'login_coach#create'
  post '/coach/logout', to: 'login_coach#logout'

  get '/coach/reset_password', to: 'reset_coach_password#new'
  post '/coach/reset_password', to: 'reset_coach_password#create'
  get '/coach/reset_password/verify', to: 'reset_coach_password#edit'
  patch '/coach/reset_password/verify', to: 'reset_coach_password#update'
  get '/coach/resend_reset', to: 'reset_coach_password#resend'

  get '/coach/dashboard', to: 'coach#dashboard'
  get '/coach/library', to: 'coach#library'
  get '/coach/library/:technique_id', to: 'coach#technique_detail', as: 'coach_technique_detail'

  get '/coach/users', to: 'coach#users_page', as: 'coach_users_page'
  patch '/coach/users/confirm/:invitation_id', to: 'invitation#confirm_user', as: 'coach_user_confirm'
  delete '/coach/users/refuse/:invitation_id', to: 'invitation#refuse_user', as: 'coach_user_refuse'

  get '/coach/users/:user_id', to: 'coach#user_detail', as: 'coach_user_detail'

  get '/coach/edit_profile', to: 'coach#edit'
  patch '/coach/edit_profile', to: 'coach#update'

  get '/coach/edit_password', to: 'coach#edit_password'
  patch '/coach/edit_password', to: 'coach#update_password'

  get '/coach/library/:technique_id/recommend', to: 'recommendation#modal_user_recommend', as: 'coach_user_recommend'
  post '/coach/library/:technique_id/recommend', to: 'recommendation#user_recommend', as: 'coach_user_recommend_post'


  namespace :api do
    post '/user/auth', to: 'auth#user_login'
    post '/coach/auth', to: 'auth#coach_login'

    post '/user/registration', to: 'registration#user_registration'
    post '/coach/registration', to: 'registration#coach_registration'

    get '/coach/users', to: 'coach#users'
    get '/user/techniques', to: 'user#get_techniques'
    get '/user/techniques/:technique_id/steps', to: 'user#steps'

  end

end

mental_health/app/models/technique.rb
class Technique < ApplicationRecord
  enum gender: [:male, :female, :both]

  has_many :steps
  has_and_belongs_to_many :problems

  has_many :ratings
  has_many :recommendations
  has_one_attached :image
end

mental_health/app/controllers/technique_controller.rb
class TechniqueController < ApplicationController
  before_action :set_user, :set_coach

  def technique_detail
    @recommendation = @user.recommendations.find_by(technique_id: params[:technique_id])

    if @recommendation
      @total_steps = @recommendation.technique.steps.count
      next_step = params[:step_id].to_i + 1
      if next_step < @total_steps
        @recommendation.update(current_step: next_step)
        @recommendation.update(started_at: Time.zone.now) if @recommendation.started_at.nil?
        @step = Step.find_by(number: next_step)
      else
        @step = Step.find_by(number: @total_steps)
        @recommendation.update(current_step: @total_steps)
      end
    end
  end

  def restart_technique
    @recommendation = @user.recommendations.find_by(technique_id: params[:technique_id])
    if @recommendation && (@recommendation.current_step = @recommendation.technique.steps.count)
      @recommendation.update(current_step: 0, started_at: nil, finished_at: nil)
      redirect_to user_technique_detail_path(technique_id: params[:technique_id], step_id: 0)
    end
  end

  def modal_finish_technique
    respond_to do |format|
      format.html
      format.js
    end
  end

  def rate_technique
    Users::RateService.call(@user, params)
    recommendation = @user.recommendations.find_by(technique_id: params[:technique_id])
    recommendation.update(finished_at: Time.zone.now) if recommendation.finished_at.nil?
    redirect_to user_dashboard_path
  rescue ServiceError => e
    flash[:error] = e.message
    redirect_to user_dashboard_path
  end

  private

  def set_user
    @user = User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def set_coach
    @coach = Coach.find_by_id(session[:coach_id]) if session[:coach_id]
  end

end

mental_health/app/views/technique/_modal_finish_technique.html.erb
<div class="modal-header">
  <h5 class="modal-title">Congratulations!</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <p class="modal-message">You have finished completing the technique!</p>
  <p class="modal-message">Share with us your impressions and whether you like</p>
  <p class="modal-message">the technique.</p>
  <br>

  <p>Do you like this technique?</p>
</div>
<div class="modal-footer">

  <%= link_to 'I DON\'T LIKE IT', user_technique_rate_path(dislike:1), method: :post, class: "btn btn-secondary" %>
  <%= link_to 'I LIKE IT', user_technique_rate_path(like:1), method: :post, class: "btn btn-dark" %>

</div>

mental_health/app/views/technique/modal_finish_technique.js.erb
$("#modal-window").find(".modal-content")
.html("<%= j (render 'modal_finish_technique' )%>");
$("#modal-window").modal();

mental_health/app/views/technique/technique_detail.html.erb
<% content_for :content do %>

  <h6>
    <%= link_to "Go back", user_dashboard_path, class: "bi bi-chevron-left link-back" %>
  </h6>
  <br>

  <div class="row">

    <div class="col-8">
      <div class="row-width">
        <div class="row">
          <div class="col-9 mt">
            <%= @recommendation.technique.title %>
          </div>
          <div class="col-3 mt-steps">
            <%= @recommendation.current_step-1  %> steps completed
          </div>


          <div class="col-12">
            <br>
            <div class="card">
              <div class="body_pad">
                <p class="step-title-card"><%= @step.title %></p>
                <span><%= @step.body %></span>
                <br>
              </div>
            </div>
          </div>
          <div class="col-12">
            <br>
            <div class="row">
              <div class="col-4">
                <% if @recommendation.current_step == @total_steps %>
                  <%= link_to 'RESTART', user_technique_restart_path(technique_id: @recommendation.technique.id), method: :patch, class:"get_down_link"%>
              <% end %>
              </div>
              <div class="col-4">
                Step <%= @recommendation.current_step %> of <%= @total_steps %>
              </div>
              <div class="col-4">
                <% if @recommendation.current_step == @total_steps %>
                  <%= link_to 'PASSED', user_technique_rate_modal_path,  {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#modal-window', class: "btn btn-sing-up get_down_link"}  %>
                <% else %>
                  <%= link_to 'PASSED', user_technique_detail_path(step_id: @step.number), class:"btn btn-sing-up" %>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="row-width">

        <div class="row">

          <div class="col-6 mt-s-m active-page">
            <button id="my-users">Summary</button>
          </div>
          <div class="col-6 mt-s-m">
            <button id="waiting">Message</button>
          </div>


          <div class="col-12">
            <br>
            <div class="card h-100">
              <div class="item">
                <% if @recommendation.technique.image.attached? %>
                  <img src="<%= url_for(@recommendation.technique.image) %>" class= "card-img-top" alt="...">
                <% else %>
                  <img src="<%= asset_path('no_image.png') %>" class="card-img-top" alt="...">
                <% end %>
                  <div class="tags-div-absolute">
                    <% @recommendation.technique.problems&.each do |problem|%>
                      <span class="tags-in-image "><%= problem.title%></span>
                    <% end %>
                  </div>

              </div>
              <div class="card-body">
                <h6 class="title_card"><%= @recommendation.technique.title %></h6>

                <p class="description"><%= @recommendation.technique.description %></p>
                <div class="age">Age: <strong><%= @recommendation.technique.age_range %> years</strong></div>
                <div class="gender">Gender: <strong><%= @recommendation.technique.gender %></strong></div>
                <br>
                <div class="step">Steps:<strong> <%= @total_steps %></strong></div>
                <div class="duration">Duration:<strong> <%= @recommendation.technique.duration %> hours</strong></div>
                <div class="row">
                  <div class="col-2 image-coach-techinque">
                    <% if @recommendation.coach.coach_avatar.attached? %>
                      <img src="<%= url_for(@recommendation.coach.coach_avatar) %>" class= "rounded-circle notification-avatar">
                    <% else %>
                      <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle notification-avatar">
                    <% end %>
                  </div>
                  <div class="col-10 name-coach-techinque">
                    <%= @recommendation.coach.name %>
                  </div>
                </div>
                <ul class="hr">
                  <li><i class="bi bi-people"></i> <%= Recommendation.where(technique_id: @recommendation.technique.id).count%></li>
                  <li><i class="bi bi-hand-thumbs-up"></i> <%= @recommendation.technique.ratings.where(mark: 1).count %></li>
                  <li><i class="bi bi-hand-thumbs-down"></i>  <%= @recommendation.technique.ratings.where(mark: -1).count %></li>
                </ul>
              </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  </div>
  <br>



<% end %>
<%= render template: "user/base" %>