mental_health/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home_page#show'

  ###################### USER ###################################
  get '/user/registration', to: 'registration_user#new'
  post '/user/registration', to: 'registration_user#create'
  get '/user/registration/verify', to: 'registration_user#edit'
  patch '/user/registration/verify', to: 'registration_user#update'
  get '/user/resend', to: 'registration_user#resend'
  delete '/user/destroy', to: 'registration_user#destroy'

  get '/user/login', to: 'login_user#new'
  post '/user/login', to: 'login_user#create'
  post '/user/logout', to: 'login_user#logout'

  get '/user/reset_password', to: 'reset_user_password#new'
  post '/user/reset_password', to: 'reset_user_password#create'
  get '/user/reset_password/verify', to: 'reset_user_password#edit'
  patch '/user/reset_password/verify', to: 'reset_user_password#update'
  get '/user/resend_reset', to: 'reset_user_password#resend'

  get '/user/dashboard', to: 'user#dashboard'
  get '/user/dashboard/:technique_id/step/:step_id', to: 'technique#technique_detail', as: 'user_technique_detail'
  patch '/user/dashboard/:technique_id/restart', to: 'technique#restart_technique', as: 'user_technique_restart'
  get '/user/dashboard/:technique_id/rate', to: 'technique#modal_finish_technique', as: 'user_technique_rate_modal'
  post '/user/dashboard/:technique_id/rate', to: 'technique#rate_technique', as: 'user_technique_rate'

  get '/user/edit_profile', to: 'user#edit'
  patch '/user/edit_profile', to: 'user#update'
  get '/user/edit_password', to: 'user#edit_password'
  patch '/user/edit_password', to: 'user#update_password'

  get 'user/coaches', to: 'user#coaches_page', as: 'user_coaches_page'
  get 'user/coaches/invitation/:coach_id', to: 'invitation#modal_send_invitation', as: 'user_send_invitation'
  post 'user/coaches/invitation/:coach_id', to: 'invitation#send_invitation', as: 'user_send_invitation_verify'

  get 'user/coaches/cancel_invitation', to: 'invitation#modal_cancel_invitation', as: 'user_cancel_invitation'
  delete 'user/coaches/cancel_invitation', to: 'invitation#cancel_invitation', as: 'user_cancel_invitation_verify'

  get '/user/dashboard/end_coop', to: 'invitation#modal_end_cooperation', as: 'user_end_coach_cooperation'
  delete '/user/dashboard/end_coop', to: 'invitation#end_cooperation', as: 'user_end_coach_cooperation_verify'

  get '/user/techniques', to: 'user#techniques'


  ############### COACH #####################################
  get '/coach/registration', to: 'registration_coach#new'
  post '/coach/registration', to: 'registration_coach#create'
  get '/coach/registration/verify', to: 'registration_coach#edit'
  patch '/coach/registration/verify', to: 'registration_coach#update'
  get '/coach/resend', to: 'registration_coach#resend'
  delete '/coach/destroy', to: 'registration_coach#destroy'

  get '/coach/login', to: 'login_coach#new'
  post '/coach/login', to: 'login_coach#create'
  post '/coach/logout', to: 'login_coach#logout'

  get '/coach/reset_password', to: 'reset_coach_password#new'
  post '/coach/reset_password', to: 'reset_coach_password#create'
  get '/coach/reset_password/verify', to: 'reset_coach_password#edit'
  patch '/coach/reset_password/verify', to: 'reset_coach_password#update'
  get '/coach/resend_reset', to: 'reset_coach_password#resend'

  get '/coach/dashboard', to: 'coach#dashboard'
  get '/coach/library', to: 'coach#library'
  get '/coach/library/:technique_id', to: 'coach#technique_detail', as: 'coach_technique_detail'

  get '/coach/users', to: 'coach#users_page', as: 'coach_users_page'
  patch '/coach/users/confirm/:invitation_id', to: 'invitation#confirm_user', as: 'coach_user_confirm'
  delete '/coach/users/refuse/:invitation_id', to: 'invitation#refuse_user', as: 'coach_user_refuse'

  get '/coach/users/:user_id', to: 'coach#user_detail', as: 'coach_user_detail'

  get '/coach/edit_profile', to: 'coach#edit'
  patch '/coach/edit_profile', to: 'coach#update'

  get '/coach/edit_password', to: 'coach#edit_password'
  patch '/coach/edit_password', to: 'coach#update_password'

  get '/coach/library/:technique_id/recommend', to: 'recommendation#modal_user_recommend', as: 'coach_user_recommend'
  post '/coach/library/:technique_id/recommend', to: 'recommendation#user_recommend', as: 'coach_user_recommend_post'


  namespace :api do
    post '/user/auth', to: 'auth#user_login'
    post '/coach/auth', to: 'auth#coach_login'

    post '/user/registration', to: 'registration#user_registration'
    post '/coach/registration', to: 'registration#coach_registration'

    get '/coach/users', to: 'coach#users'
    get '/user/techniques', to: 'user#get_techniques'
    get '/user/techniques/:technique_id/steps', to: 'user#steps'

  end

end

mental_health/app/controllers/registration_user_controller.rb
class RegistrationUserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_permitted_params)

    if @user.save
      session[:user_id] = @user.id
      RegistrationVerifyMailer.with(user: @user).user_verify_email.deliver_now
      render :create
    else
      render :new
    end
  end

  def edit
    @problems = Problem.all
    @user = User.find_signed!(params[:token], purpose: 'user_registration_verify')

  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to user_registration_path, alert: 'Your token has expired. Please try again.'
  end

  def update
    @user = User.find_by(id: session[:user_id]) if session[:user_id]

    if @user.update(user_update_params)
      params[:user][:problems]&.each do |problem|
        @user.problems << Problem.find_by(title: problem)
      end
      redirect_to user_dashboard_path
    else
      render :edit
    end
  end

  def resend
    @user = User.find_by_id(session[:user_id]) if session[:user_id]
    RegistrationVerifyMailer.with(user: @user).user_verify_email.deliver_now
    render :create
  end

  def destroy
    User.find_by_id(session[:user_id]).destroy if session[:user_id]
    session[:user_id] = nil
    redirect_to user_registration_path
  end

  private

  def user_permitted_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:user_avatar, :age, :gender)
  end
end

mental_health/app/views/registration_user/create.html.erb
<body>
<nav class="navbar navbar-expand-lg nav_background fixed-top">
  <div class="container-fluid pad">
    <a class="navbar-brand logo logo-button" href="#">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
<div class="conteiner">
  <h6>
    <%= button_to "Go back", user_destroy_path, method: :delete, class: "bi bi-chevron-compact-left link-back" %>
  </h6>
  <div class="mail-icon">
    <i class="bi bi-envelope-open"></i>
  </div>
  <p class="verify">Verify your e-mail</p>
  <p class="verify-text">Click on the link that was sent to the email address you entered: <strong><%= @user.email %></strong></p>
  <p class="verify-text">to confirm your email address and continue the registration process.</p>
  <br>
  <p class="lb"></p>
  <br>
  <br>
  <p class="verify-text">Did not receive the e-mail? Check your spam filter or</p>

  <p class="verify-text"><strong><%= link_to 'resend', user_resend_path, class: "resend-link" %></strong></p>

</div>
</body>

mental_health/app/views/registration_user/edit.html.erb
<body>
<nav class="navbar navbar-expand-lg nav_background fixed-top">
  <div class="container-fluid pad">
    <a class="navbar-brand logo logo-button" href="#">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
<div class="conteiner">
  <h4 class="wait-title">Hello, <strong><%= @user.name %></strong>!</h4>
  <p class="help-text">You have registered as a User in our system.</p>
  <p class="help-text">Please, share some personal information about you so that we can</p>
  <p class="help-text">personalize your onboarding experience</p>
  <%= form_with multipart: true, model: @user, class: "form-registration", url: user_registration_verify_path do |f| %>
    <div class="image-input">
      <img class="rounded-circle" id="output" src="<%= asset_path('camera.png') %>"/>
      <label for="avatar">
        <h4 class="upload">Upload profile photo</h4>
        <p class="upload-text">Image format should be png, jpg</p>
        <p class="upload-text">no more than 5 Mb</p>
      </label>
      <input type="file" accept="image/*" name="user[user_avatar]" id="avatar" onchange="loadFile(event)">
      <script>
          var loadFile = function (event) {
              var output = document.getElementById('output');
              output.src = URL.createObjectURL(event.target.files[0]);
              output.onload = function () {
                  URL.revokeObjectURL(output.src) // free memory
              }
          };
      </script>
    </div>
    <div class="form-group">
      <%= f.label 'Age', class: "labels" %>
      <%= f.text_field :age, class: "field form-control" %>
    </div>
    <br>

    <label class="labels">Gender</label>
    <div class="sign_for_gender">
      <label class="link_for_gender male" for="male">
        <input type="radio" class="female" name="user[gender]" id="male" value="male">
        <p class="margin-none">MALE</p>
      </label>


      <label class="link_for_gender female" for="female">
        <input type="radio" class="female" name="user[gender]" id="female" value="female" checked>
        <p class="margin-none">FEMALE</p>
      </label>
    </div>
    <br>
    <div class="form-group">
      <label class="labels" for="tags">What problem would you like to solve?</label>
      <select class="form-control select2-multi" name="user[problems][]" multiple="multiple">
        <% @problems.each do |data| %>
          <option value="<%= data.title %>"><%= data.title %></option>
        <% end %>
      </select>
    </div>
    <br>
    <script>
        $('.select2-multi').select2();
    </script>

    <%= f.submit 'CONTINUE', class: "btn btn-sing-up marge-top" %>
  <% end %>
</div>
</body>

mental_health/app/views/registration_user/new.html.erb
<body>
<nav class="navbar navbar-expand-lg nav_background fixed-top">
  <div class="container-fluid pad">
    <a class="navbar-brand logo logo-button" href="#">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
<div class="conteiner">
  <h4 class="create">Create account</h4>
  <div class="sign_in">
    <div class="ask">Already have an account?</div>
    <div class="link"><%= link_to 'Login', user_login_path, class: "custom"%></div>
  </div>



  <%= form_with model: @user, class: "form-registration", url: user_registration_path do |f| %>
    <div class="sign_for marge-top">
      <div class="link_for active">USER</div>
<!--       <div class="link_for">COACH</div>-->
      <%= link_to 'COACH', coach_registration_path, class: 'link_for' %>
    </div>
    <br>
    <%# if alert %>
<!--      <p class="alert"><%#= alert%></p>-->
    <%# end %>
    <%# invalid = @user.errors.include?(:name) %>

    <div class="form-group">
      <%= f.label :name, class: "labels" %>
      <%= f.text_field :name, class: "field form-control "%>
      <%# if invalid %>
<!--        <div class="invalid-feedback d-block">-->
          <%# @user.errors.full_messages_for(:name).each do |error_message| %>
<!--            <%#= error_message %>.-->
          <%# end %>
<!--        </div>-->
      <%# end %>
    </div>
    <br>
    <%# invalid = @user.errors.include?(:email) %>

    <div class="form-group">
      <%= f.label :email, class: "labels" %>
      <%= f.text_field :email, class: "field form-control" %>
      <%# if invalid %>
<!--        <div class="invalid-feedback d-block">-->
          <%# @user.errors.full_messages_for(:email).each do |error_message| %>
<!--            <%#= error_message %>.-->
          <%# end %>
<!--        </div>-->
      <%# end %>
    </div>
    <br>

    <%# invalid = @user.errors.include?(:password) %>

    <div class="form-group" data-controller="password-toggle">
      <%= f.label :password, class: "labels" %>
      <%= f.password_field :password, class: "field form-control " %>
      <%# if invalid %>
<!--        <div class="invalid-feedback d-block">-->
          <%# @user.errors.full_messages_for(:password).each do |error_message| %>
<!--            <%#= error_message %>.-->
          <%# end %>
<!--        </div>-->
      <%# end %>
    </div>
    <br>

    <%# invalid = @user.errors.include?(:password_confirmation) %>

    <div class="form-group" data-controller="password-toggle">
      <%= f.label :password_confirmation, class: "labels" %>
      <%= f.password_field :password_confirmation, class: "field form-control " %>
      <%# if invalid %>
<!--        <div class="invalid-feedback d-block">-->
          <%# @user.errors.full_messages_for(:password_confirmation).each do |error_message| %>
<!--            <%#= error_message %>.-->
          <%# end %>
<!--        </div>-->
      <%# end %>
    </div>
    <br>

    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="flexCheckDefault" name="user[agree]">
      <label class="form-check-label font" for="flexCheckDefault">
        I've read and agree with <strong>Terms of Services</strong> and our <strong>Privacy Policy</strong>
      </label>
    </div>

    <!-- <p class="marge-top">I've read and agree with Terms of Services and our Privacy Policy</p> -->
    <%= f.submit 'SIGN UP', class: "btn btn-sing-up marge-top"%>
  <% end %>
  <div class="sign-with">
    <div class="with">
      or Sign in with
    </div>
    <div class="badge-with">
      <%#= button_to '/auth/google_oauth2', class: "icon-color" do %>
        <i class="bi bi-facebook"></i>
        <i class="bi bi-google"></i>

      <%# end %>

    </div>
  </div>
</div>
</body>