mental_health/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'home_page#show'

  ###################### USER ###################################
  get '/user/registration', to: 'registration_user#new'
  post '/user/registration', to: 'registration_user#create'
  get '/user/registration/verify', to: 'registration_user#edit'
  patch '/user/registration/verify', to: 'registration_user#update'
  get '/user/resend', to: 'registration_user#resend'
  delete '/user/destroy', to: 'registration_user#destroy'

  get '/user/login', to: 'login_user#new'
  post '/user/login', to: 'login_user#create'
  post '/user/logout', to: 'login_user#logout'

  get '/user/reset_password', to: 'reset_user_password#new'
  post '/user/reset_password', to: 'reset_user_password#create'
  get '/user/reset_password/verify', to: 'reset_user_password#edit'
  patch '/user/reset_password/verify', to: 'reset_user_password#update'
  get '/user/resend_reset', to: 'reset_user_password#resend'

  get '/user/dashboard', to: 'user#dashboard'
  get '/user/dashboard/:technique_id/step/:step_id', to: 'technique#technique_detail', as: 'user_technique_detail'
  patch '/user/dashboard/:technique_id/restart', to: 'technique#restart_technique', as: 'user_technique_restart'
  get '/user/dashboard/:technique_id/rate', to: 'technique#modal_finish_technique', as: 'user_technique_rate_modal'
  post '/user/dashboard/:technique_id/rate', to: 'technique#rate_technique', as: 'user_technique_rate'

  get '/user/edit_profile', to: 'user#edit'
  patch '/user/edit_profile', to: 'user#update'
  get '/user/edit_password', to: 'user#edit_password'
  patch '/user/edit_password', to: 'user#update_password'

  get 'user/coaches', to: 'user#coaches_page', as: 'user_coaches_page'
  get 'user/coaches/invitation/:coach_id', to: 'invitation#modal_send_invitation', as: 'user_send_invitation'
  post 'user/coaches/invitation/:coach_id', to: 'invitation#send_invitation', as: 'user_send_invitation_verify'

  get 'user/coaches/cancel_invitation', to: 'invitation#modal_cancel_invitation', as: 'user_cancel_invitation'
  delete 'user/coaches/cancel_invitation', to: 'invitation#cancel_invitation', as: 'user_cancel_invitation_verify'

  get '/user/dashboard/end_coop', to: 'invitation#modal_end_cooperation', as: 'user_end_coach_cooperation'
  delete '/user/dashboard/end_coop', to: 'invitation#end_cooperation', as: 'user_end_coach_cooperation_verify'

  get '/user/techniques', to: 'user#techniques'


  ############### COACH #####################################
  get '/coach/registration', to: 'registration_coach#new'
  post '/coach/registration', to: 'registration_coach#create'
  get '/coach/registration/verify', to: 'registration_coach#edit'
  patch '/coach/registration/verify', to: 'registration_coach#update'
  get '/coach/resend', to: 'registration_coach#resend'
  delete '/coach/destroy', to: 'registration_coach#destroy'

  get '/coach/login', to: 'login_coach#new'
  post '/coach/login', to: 'login_coach#create'
  post '/coach/logout', to: 'login_coach#logout'

  get '/coach/reset_password', to: 'reset_coach_password#new'
  post '/coach/reset_password', to: 'reset_coach_password#create'
  get '/coach/reset_password/verify', to: 'reset_coach_password#edit'
  patch '/coach/reset_password/verify', to: 'reset_coach_password#update'
  get '/coach/resend_reset', to: 'reset_coach_password#resend'

  get '/coach/dashboard', to: 'coach#dashboard'
  get '/coach/library', to: 'coach#library'
  get '/coach/library/:technique_id', to: 'coach#technique_detail', as: 'coach_technique_detail'

  get '/coach/users', to: 'coach#users_page', as: 'coach_users_page'
  patch '/coach/users/confirm/:invitation_id', to: 'invitation#confirm_user', as: 'coach_user_confirm'
  delete '/coach/users/refuse/:invitation_id', to: 'invitation#refuse_user', as: 'coach_user_refuse'

  get '/coach/users/:user_id', to: 'coach#user_detail', as: 'coach_user_detail'

  get '/coach/edit_profile', to: 'coach#edit'
  patch '/coach/edit_profile', to: 'coach#update'

  get '/coach/edit_password', to: 'coach#edit_password'
  patch '/coach/edit_password', to: 'coach#update_password'

  get '/coach/library/:technique_id/recommend', to: 'recommendation#modal_user_recommend', as: 'coach_user_recommend'
  post '/coach/library/:technique_id/recommend', to: 'recommendation#user_recommend', as: 'coach_user_recommend_post'


  namespace :api do
    post '/user/auth', to: 'auth#user_login'
    post '/coach/auth', to: 'auth#coach_login'

    post '/user/registration', to: 'registration#user_registration'
    post '/coach/registration', to: 'registration#coach_registration'

    get '/coach/users', to: 'coach#users'
    get '/user/techniques', to: 'user#get_techniques'
    get '/user/techniques/:technique_id/steps', to: 'user#steps'

  end

end

mental_health/app/models/coach.rb
class Coach < ApplicationRecord
  enum gender: [:male, :female], _prefix: :gender

  has_secure_password

  validates :password,
            presence: true,
            format: { with: /\A(?=.*[a-zA-Z])(?=.*[0-9]).{8,}\z/ },
            allow_nil: true
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A.+@.+\..+\z/ }
  validates :age, presence: false
  validates :abouts, presence: false
  validates :gender, presence: false

  has_many :experiences
  has_many :certificates
  has_many :diplomas
  has_many :social_networks
  has_and_belongs_to_many :problems

  has_many :invitations
  has_many :users, through: :invitations

  has_many :notifications
  has_many :recommendations

  has_one_attached :coach_avatar
end

mental_health/app/controllers/api/coach_controller.rb
module Api
  class CoachController < ::ApiController
    before_action :authorize_coach_request

    def users
      invitations = @coach.invitations.where(status: true)
      users = []

      if users
        invitations.each { |invitation| users << invitation.user }
        render json: users, status: :ok
      else
        render json: 'No confirmed users', status: :no_content
      end
    end

  end
end

mental_health/app/controllers/coach_controller.rb
class CoachController < ApplicationController
  before_action :check_coach_login!, :set_coach

  def edit
    @problems = Problem.all
  end

  def update
    Coaches::EditProfileService.call(@coach, params)
    @coach.notifications.create(description: 'You changed your profile settings', status: 1)
    redirect_to coach_dashboard_path

  rescue ServiceError => e
    flash[:error] = e.message
    render :edit

  end

  def edit_password
  end

  def update_password
    Coaches::PasswordUpdateService.call(@coach, params)
    @coach.notifications.create(description: 'You changed your password', status: 1)
    redirect_to coach_dashboard_path
  rescue ServiceError => e
    flash[:error] = e.message
    render :edit_password
  end

  def dashboard
    @notifications = @coach.notifications.order('created_at DESC')
    @invitations = @coach.invitations.where(status: true)

    unique_techniques_id = @coach.recommendations.pluck(:technique_id).uniq
    unique_techniques = Technique.where(id: unique_techniques_id)
    @techniques = unique_techniques
    @techniques_used = unique_techniques_id.count
    @techniques_with_like = unique_techniques.select { |t| t.ratings.where(mark: 1).count.positive? }.count
    @progress = users_progress @invitations
  end

  def library
    @problems = Problem.all
    if params[:filter]
      techniques = Technique.all
      techniques_problems = filter_problems(params[:filter][:problems], techniques)
      techniques_gender = filter_gender(params[:filter][:gender], techniques_problems)
      @techniques = filter_status(params[:filter][:status], @coach.id, techniques_gender)
    else
      @techniques = Technique.all
    end
    @techniques
  end

  def technique_detail
    @technique = Technique.find_by_id(params[:technique_id])
    @steps = @technique.steps
  end

  def users_page
    @invitations = @coach.invitations
    @notifications = @coach.notifications.where.not(user_id: nil).order('created_at DESC')
    @progress = users_progress @invitations
  end

  def user_detail
    @user = User.find_by_id(params[:user_id])
    @invitation = @coach.invitations.find_by(user_id: @user.id)
    redirect_to coach_users_page_path unless @user && @invitation && @invitation.status
    @notifications = @coach.notifications.where(user_id: @user.id).order('created_at DESC')
  end

  private

  def set_coach
    @coach = Coach.find_by_id(session[:coach_id])
  end

  def users_progress(invitations)
    users_technique = Hash.new { |hash, key| hash[key] = [] }
    invitations.each do |invitation|
      users_technique[invitation.user.email] = []
      temp = invitation.user.recommendations
                       .where.not(started_at: nil).where(finished_at: nil)
      temp&.each { |rec| users_technique[invitation.user.email] << rec.technique.title }
    end
    users_technique
  end

  def coach_password_permit_params
    params.require(:coach).permit(:password, :password_confirmation)
  end

  def filter_gender(params, techniques)
    params ? techniques&.where(gender: params) : techniques
  end

  def filter_problems(params, techniques)
    params ? Problem.find_by(title: params).techniques : techniques
  end

  def filter_status(params, coach_id, techniques)
    return techniques if params.nil?
    t_p = []

    params.each do |param|
      case param
      when 'recommend'
        ## recommend if coach recommend this technique before
        temp = Recommendation.where(coach_id: coach_id).pluck(:technique_id).uniq
        techniques = techniques.where(id: temp)
      when 'new'
        techniques = techniques.where('created_at >= ?', 1.week.ago)
      when 'popular'
        ## popular if count of users on technique >= 50% users
        users_count = User.all.count / 2
        techniques&.each do |technique|
          t_p << technique if Recommendation.where(technique_id: technique.id).count >= users_count
        end
        t_p
      end
    end
    t_p == [] ? techniques : t_p
  end
end

mental_health/app/views/coach/add_modal_window.js.erb
$("#modal-window").find(".modal-content")
.html("<%= j (render @html_name )%>");
$("#modal-window").modal();

mental_health/app/views/coach/base.html.erb
<nav class="navbar navbar-expand-lg nav_background fixed-top">
  <div class="container-fluid pad">
    <a class="navbar-brand logo logo-button" href="#">Logo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'Dashboard', coach_dashboard_path, class: "nav-link nav-link-style"%>
        <%= link_to 'My users', coach_users_page_path, class: "nav-link nav-link-style"%>
        <%= link_to 'Library', coach_library_path, class: "nav-link nav-link-style"%>
      </div>
    </div>
    <div class="d-flex">
      <div class="envelope-block"><i class="bi bi-envelope"></i></div>

      <div class="bell-block">
        <i class="bi bi-bell" ></i>

      </div>
      <div class="me-3 dropdown">
        <% if @coach.coach_avatar.attached? %>
          <img src="<%= url_for(@coach.coach_avatar) %>" class= "rounded-circle size-image" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
        <% else %>
          <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle size-image" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
        <% end %>
        <ul class="dropdown-menu">
          <li><%= link_to 'Edit Personal Information', coach_edit_profile_path, class: "dropdown-item" %></li>
          <li><hr class="dropdown-divider"></li>
          <li><%= link_to 'Change Password', coach_edit_password_path, class: "dropdown-item" %></li>
        </ul>
      </div>
      <%= button_to 'LOG OUT', coach_logout_path, class: "btn btn-sing-in" %>
    </div>
  </div>
</nav>

<div class="content-block">

  <%= content_for?(:content) ? yield(:content) : yield %>


</div>

mental_health/app/views/coach/dashboard.html.erb
<% content_for :content do %>

  <div class="row">
    <div class="col-8">
      <div class="row">
        <div class="col-3">
          <div class="total-current-box-coach">
            <div class="size-total-coach"><i class="bi bi-people"></i></div>
            <p class="tt">Total number </p>
            <p class="tt">of users</p>
            <p class="coach-stats"><%= User.all.count %></p>
          </div>

        </div>
        <div class="col-3">
          <div class="total-current-box-coach">
            <div class="size-total-coach"><i class="bi bi-person"></i></div>
            <p class="tt">Current number</p>
            <p class="tt">of users</p>
            <p class="coach-stats"><%= @coach.invitations.where(status: true).count %></p>
          </div>
        </div>
        <div class="col-3">
          <div class="total-current-box-coach">
            <div class="size-total-coach"><i class="bi bi-card-list"></i></div>
            <p class="tt">Total number of</p>
            <p class="tt">techniques used</p>
            <p class="coach-stats"><%= @techniques_used %></p>
          </div>
        </div>
        <div class="col-3">
          <div class="total-current-box-coach">
            <div class="size-total-coach"><i class="bi bi-hand-thumbs-up"></i></div>
            <p class="tt">Total number of</p>
            <p class="tt">techniques with likes</p>
            <p class="coach-stats"><%= @techniques_with_like %></p>
          </div>
        </div>
      </div>

      <div class="row-width">
        <div class="row">
          <div class="col-11 mt">
            My users
          </div>
          <div class="col-1 sa">
            See All
          </div>
        </div>
      </div>
      <br>

      <div class="row">
        <% if @invitations %>
          <% @invitations.each do |invitation| %>
              <div class="col-6">
                <br>
                <div class="card">
                  <div class="body">
                    <div class="small-card">
                      <div class="image-avatar-small">
                        <% if invitation.user.user_avatar.attached? %>
                          <img src="<%= url_for(invitation.user.user_avatar) %>" class="rounded-circle avatar-coach-users">
                        <% else %>
                          <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle avatar-coach-users">
                        <% end %>

                      </div>
                      <div class="name-coach">
                        <span class="coach-name"><%= invitation.user.name %></span><br>
                        <span class="status">Current user</span>
                        <p class="coach-info-left"><%= invitation.user.age %> years | <%= invitation.user.gender %></p>
                        <div class="edit-prof-coach">
                          <i class="bi bi-envelope"></i>
                        </div>
                      </div>
                      <div class="about-user">
                        <p class="tages-info">Problems</p>
                        <% invitation.user.problems.each do |problem|%>
                          <span class="tags"><%= problem.title%></span>
                        <% end %>
                        <p class="tages-info">Techniques in process</p>
                        <% if @progress[invitation.user.email] == [] %>
                          <p class="completed_techniques">All techniques completed</p>
                        <% else %>
                          <% @progress[invitation.user.email].each do |technique_name|%>
                            <p class="user-t-info"><%= technique_name %></p>
                          <% end %>
                        <% end %>
                        <div class="see-detail-button"><%= link_to 'SEE DETAILS', coach_user_detail_path(user_id: invitation.user.id), class: "get_down_link"%></div>

                      </div>
                    </div>
                  </div>
                </div>
                <br>
              </div>
          <% end %>
        <% else %>
          <p>You don't confirm any invitayions!</p>
        <% end %>

      </div>

      <div class="row-width">
        <div class="row">
          <div class="col-11 mt">
            Techniques
          </div>
          <div class="col-1 sa">
            See All
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <% @techniques.each do |technique|%>
          <div class="col-6 distance">
            <div class="card h-100">
              <div class="item">

                <% if technique.image.attached? %>
                  <img src="<%= url_for(technique.image) %>" class= "card-img-top" alt="...">
                <% else %>
                  <img src="<%= asset_path('no_image.png') %>" class="card-img-top" alt="...">
                <% end %>

                  <div class="tags-div-absolute">
                    <% technique.problems&.each do |problem|%>
                      <span class="tags-in-image "><%= problem.title%></span>
                    <% end %>
                  </div>

              </div>
              <div class="card-body">
                <h6 class="title_card"><%= technique.title %></h6>
                <p class="description"><%= technique.description %></p>
                <div class="age">Age: <strong><%= technique.age_range %> years</strong></div>
                <div class="gender">Gender:<strong> <%= technique.gender %></strong></div>
                <br>
                <div class="step">Steps: <strong><%= technique.steps.count %></strong></div>
                <div class="duration">Duration: <strong><%= technique.duration %> hours</strong></div>
                <% count_recs = @coach.recommendations.where(technique_id: technique.id).count %>
                <% if count_recs <= 11 %>
                  <div class="users-count">
                    <%= count_recs %> users
                  </div>
                <% else %>
                  <div class="users-count">11+ users</div>
                <% end %>
                <ul class="hr">
                  <li><i class="bi bi-people"></i> <%= technique.recommendations.count%></li>
                  <li><i class="bi bi-hand-thumbs-up"></i> <%= technique.ratings.where(mark: 1).count%></li>
                  <li><i class="bi bi-hand-thumbs-down"></i> <%=  technique.ratings.where(mark: -1).count%></li>
                  <li class="start-button"><%= link_to 'SEE DETAILS', coach_technique_detail_path(technique_id: technique.id),class: "get_down_link" %></li>
                </ul>
              </div>
            </div>

          </div>
        <% end %>

      </div>
    </div>
    <div class="col-4">
      <div class="card pc">
        <div class="body">
          <div class="small-card">
            <div class="image-avatar-small">

              <% if @coach.coach_avatar.attached? %>
                <img src="<%= url_for(@coach.coach_avatar) %>" class= "image-size rounded-circle ">
              <% else %>
                <img src="<%= asset_path('avatar/no_avatar.png') %>" class="image-size rounded-circle">
              <% end %>
              <div class="check-circle-dashbord"><i class="bi bi-check-circle-fill"></i></div>
            </div>
            <div class="name-coach">
              <span class="coach-name"><%= @coach.name %></span><br>
              <span class="status"><%= @coach.email %></span>
              <p class="coach-info-left"><%= @coach.age %> years | <%= @coach.gender %></p>
              <div class="edit-prof">
                <i class="bi bi-three-dots-vertical"></i>
              </div>

            </div>
            <p class="tages-info">Areas of Expertise</p>

              <% @coach.problems&.each do |problem| %>
                <span class="tags"><%= problem.title %></span>
              <% end %>

          </div>
        </div>
      </div>

      <div class="row-width">
        <div class="row">
          <div class="col-5 notifications-title">
            Notifications
          </div>
          <div class="col-7 send-me-mail">

            <div class="form-switch">
              <label class="label-for-switch">Send me an email</label>
              <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault"/>
            </div>
          </div>
        </div>
          <div class="layer">
            <% @notifications&.each do |notification| %>
              <div class="row">
                <div class="col-2 notif-avatar-block">
                <% if notification.user_id %>
                    <% if notification.user.user_avatar.attached? %>
                      <img src="<%= url_for(notification.user.user_avatar) %>" class= "rounded-circle notification-avatar">
                    <% else %>
                      <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle notification-avatar">
                    <% end %>
                <% else %>
                  <% if @coach.coach_avatar.attached? %>
                    <img src="<%= url_for(@coach.coach_avatar) %>" class= "rounded-circle notification-avatar">
                  <% else %>
                    <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle notification-avatar">
                  <% end %>
                <% end %>
                </div>
                <div class="col-7">
                  <p class="notif-text-block"><%= notification.description %></p>
                  <p class="notif-hours-block"><%= time_lasted_since(notification.created_at, notification)%></p>
                </div>
                <div class="col-3 notif-tag-block ">
                  <% if notification.status == true %>
                    <span class="badge-tag">NEW</span>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>

      </div>

    </div>
  </div>

<% end %>
<%= render template: "coach/base" %>

mental_health/app/views/coach/users_page.html.erb
<% content_for :content do %>
  <div class="row">

    <div class="col-8">
      <div class="row-width">

        <div class="row">

          <div class="col-6 my-users-page active-page">
            <button id="my-users">My users</button>
          </div>
          <div class="col-6 my-users-page">
            <button id="waiting">Waiting for confirmation (
              <%= @coach.invitations.where(status: false).count %>
              )</button>
          </div>

        </div>

        <div id="div-waiting-users">
          <div class="row">
            <% if @invitations %>
              <% @invitations&.each do |invitation| %>
                <% if invitation.status == false %>
                  <div class="col-6">
                    <br>
                    <div class="card">
                      <div class="body">
                        <div class="small-card">
                          <div class="image-avatar-small">
                            <% if invitation.user.user_avatar.attached? %>
                              <img src="<%= url_for(invitation.user.user_avatar) %>" class="rounded-circle avatar-coach-users">
                            <% else %>
                              <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle avatar-coach-users">
                            <% end %>

                          </div>
                          <div class="name-coach">
                            <span class="coach-name"><%= invitation.user.name %></span><br>
                            <span class="status">User</span>
                            <p class="coach-info-left"><%= invitation.user.age %> years | <%= invitation.user.gender %></p>
                            <% if invitation.user.about %>
                              <p class="coach-info-left"><%= invitation.user.about %></p>
                            <% end %>
                            <div class="edit-prof-coach">
                              <i class="bi bi-envelope"></i>
                            </div>
                          </div>
                          <div class="about-user">
                            <p class="tages-info">Problems</p>
                            <% invitation.user.problems&.each do |problem|%>
                              <span class="tags"><%= problem.title %></span>
                            <% end %>
                            <div class="buttons-list">
                              <%= button_to 'CONFIRM', coach_user_confirm_path(invitation.id), method: :patch, class:"button-confirm"%>
                              <%= button_to 'REFUSE', coach_user_refuse_path(invitation.id), method: :delete, class:"button-refuse" %>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <p>You don't confirm any invitations!</p>
            <% end %>

          </div>
        </div>
        <div id="div-my-users">
          <div class="row">
            <% if @invitations %>
              <% @invitations&.each do |invitation| %>
                <% if invitation.status == true %>
                  <div class="col-6">
                    <br>
                    <div class="card">
                      <div class="body">
                        <div class="small-card">
                          <div class="image-avatar-small">
                            <% if invitation.user.user_avatar.attached? %>
                              <img src="<%= url_for(invitation.user.user_avatar) %>" class="rounded-circle avatar-coach-users">
                            <% else %>
                              <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle avatar-coach-users">
                            <% end %>

                          </div>
                          <div class="name-coach">
                            <span class="coach-name"><%= invitation.user.name %></span><br>
                            <span class="status">Current user</span>
                            <p class="coach-info-left"><%= invitation.user.age %> years | <%= invitation.user.gender %></p>
                            <div class="edit-prof-coach">
                              <i class="bi bi-envelope"></i>
                            </div>
                          </div>
                          <div class="about-user">
                            <p class="tages-info">Problems</p>
                            <% invitation.user.problems&.each do |problem|%>
                              <span class="tags"><%= problem.title %></span>
                            <% end %>
                            <p class="tages-info">Techniques in process</p>
                            <% if @progress[invitation.user.email] == [] %>
                              <p class="completed_techniques">All techniques completed</p>
                            <% else %>
                              <% @progress[invitation.user.email].each do |technique_name|%>
                                <p class="user-t-info"><%= technique_name %></p>
                              <% end %>
                            <% end %>
                            <div class="see-detail-button"><%= link_to 'SEE DETAILS', coach_user_detail_path(user_id: invitation.user.id), class: "get_down_link"%></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            <% else %>
              <p>You don't confirm any invitations!</p>
            <% end %>

          </div>
        </div>


      </div>
    </div>
    <script type="text/javascript">
        $('#waiting').click(function (){
            $('#div-waiting-users').show();
            $('#div-my-users').hide();
        });
        $('#my-users').click(function (){
            $('#div-my-users').show();
            $('#div-waiting-users').hide();
        });
    </script>

    <div class="col-4">

      <div class="row-width">
        <div class="row">
          <div class="col-12 notifications-title">
            User's Notifications
          </div>

        </div>
          <div class="layer">
            <% @notifications&.each do |notification| %>
              <div class="row">
                <div class="col-2 notif-avatar-block">
                  <% if notification.user_id %>
                    <% if notification.user.user_avatar.attached? %>
                      <img src="<%= url_for(notification.user.user_avatar) %>" class= "rounded-circle notification-avatar">
                    <% else %>
                      <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle notification-avatar">
                    <% end %>
                  <% else %>
                    <% if @coach.coach_avatar.attached? %>
                      <img src="<%= url_for(@coach.coach_avatar) %>" class= "rounded-circle notification-avatar">
                    <% else %>
                      <img src="<%= asset_path('avatar/no_avatar.png') %>" class="rounded-circle notification-avatar">
                    <% end %>
                  <% end %>

                </div>
                <div class="col-7">
                  <p class="notif-text-block"><%= notification.description %></p>
                  <p class="notif-hours-block"><%= time_lasted_since(notification.created_at, notification)%></p>
                </div>
                <div class="col-3 notif-tag-block ">
                  <% if notification.status == true %>
                    <span class="badge-tag">NEW</span>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>

      </div>

    </div>

  </div>

<% end %>
<%= render template: "coach/base" %>